name: stale-branch-action
description: Clean up stale branches in GitHub Actions

inputs:
  expiration-days:
    description: Expiration in days
    required: true
  ref-prefix:
    description: Prefix of refs
    required: false
    default: refs/heads/
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/index.js'
