name: stale-branch-action
description: Clean up stale branches in GitHub Actions

inputs:
  expiration-days:
    description: Expiration in days
    required: true
  ref-prefix:
    description: Prefix of refs
    required: false
    default: refs/heads/
  dry-run:
    description: Set true if dry-run
    required: true
    default: 'false'
  ignore-deletion-errors:
    description: Ignore any errors of git push origin --delete
    required: true
    default: 'false'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  stale-refs:
    description: Stale ref names (multiline string)

runs:
  using: 'node16'
  main: 'dist/index.js'
